version: '2'

volumes:
  database:
  static_files:
  media_files:

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - web
    volumes_from:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  web:
    image: pando85/openeats:latest
    restart: unless-stopped
    depends_on:
      - database
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=0 # log into console
      - DEBUG=False
      - DATABASE_NAME=openeats
      - DATABASE_USER=openeats
      - DATABASE_PASSWORD=admin
      - TIME_ZONE=Europe/Madrid
      - ALLOWED_HOST=localhost
      - SECRET_KEY=tk1igapawp92muz4vw4g5q20nosgce11bw2s343jouyq9ljgk33jh
      - OETITLE=OpenEats2 Dev
      - DEFAULT_FROM_EMAIL=
      - EMAIL_HOST=
      - EMAIL_HOST_USER=
      - EMAIL_HOST_PASSWORD=
      - EMAIL_PORT=
      - EMAIL_USE_TLS=False
    volumes:
      - static_files:/usr/src/app/openeats/static
      - media_files:/usr/src/app/openeats/site-media
    command: ["/usr/local/bin/gunicorn", "openeats.wsgi:application", "-b :8000", "-w 6", "-t 5000"]

  database:
    image: postgres:9.6
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql
    environment:
      - POSTGRES_DB=openeats
      - POSTGRES_USER=openeats
      - POSTGRES_PASSWORD=admin
    expose:
      - "5432"

